message : hello
spring:
  kafka:
    properties:
      request.timeout.ms: 605000
      session.timeout.ms: 600000
      max.poll.interval.ms: 450000
    consumer:
      auto-offset-reset: earliest
      group-id: routerGroup
      enable-auto-commit: false
      heartbeat-interval: 300000
    listener:
      #Note: To actually utilize the number of threads set below, we need at least this number of partitions. We can either
      #set the number of partitions manually, or let kafka dynamically add partitions (and we'll have concurrency only when required)
      concurrency: 10
